theme: jekyll-theme-dinky
title: UDA-Part
description: UDA-Part is a comprehensive part segmentation dataset that provides detailed annotations on 3D CAD models, synthetic images, and real test images.
